# Generated by Django 6.0.6 on 2026-07-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='FuelGo', max_length=255)),
                ('support_email', models.EmailField(default='support@fuelgo.co.tz', max_length=254)),
                ('support_phone', models.CharField(default='+255 700 000 000', max_length=50)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('max_radius', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('order_timeout', models.IntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Platform settings',
            },
        ),
    ]
