# Generated by Django 6.0.6 on 2026-07-01 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_driver_is_approved_driver_licence_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Kerosene', 'Kerosene')], max_length=20)),
                ('litres_available', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('capacity', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('price_per_litre', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='accounts.station')),
            ],
        ),
    ]
