# Generated by Django 6.0.6 on 2026-06-24 09:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Phone number must be 9 digits', regex='^\\d{9}$')])),
                ('license_number', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Driver license must be 11 digits', regex='^\\d{11}$')])),
                ('license_no', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Business license must be 12 digits', regex='^\\d{12}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
