# Generated by Django 6.0.6 on 2026-06-29 22:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='address',
            field=models.TextField(default='No address provided'),
        ),
        migrations.AddField(
            model_name='station',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
