# Generated by Django 6.0.6 on 2026-06-30 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationreview',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order'),
        ),
        migrations.AddField(
            model_name='stationreview',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.station'),
        ),
    ]
