# Generated by Django 6.0.6 on 2026-07-01 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='licence_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='on_duty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='accounts.station'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='plate',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
