# Generated by Django 6.0.6 on 2026-06-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_station_address_station_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='fuel_types',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='station',
            name='licence_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='station',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
