# Generated by Django 6.0.6 on 2026-06-25 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role_alter_profile_license_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 9 digits.', regex='^\\d{9}$')]),
        ),
    ]
