# Generated by Django 6.0.6 on 2026-07-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_driver_is_approved_driver_licence_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='station',
            name='fuel_types',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='station',
            name='licence_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='open', max_length=10),
        ),
    ]
