# Generated by Django 6.0.6 on 2026-06-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_station_fuel_types_station_licence_no_station_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
