# Generated by Django 6.0.6 on 2026-06-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_station_is_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='fuel_types',
        ),
        migrations.RemoveField(
            model_name='station',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='station',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='station',
            name='licence_no',
        ),
        migrations.RemoveField(
            model_name='station',
            name='phone',
        ),
        migrations.AddField(
            model_name='station',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
