# Generated by Django 6.0.6 on 2026-07-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_driver_status_driver_vehicle_type_station_fuel_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='delivery_radius',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='station',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='station',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='station',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
